version: "3.9"
services:
  mlflow_back:
    image: mlflow-back
    container_name: mlflow-back
    build: mlflow/.
    # ports:
    #   - "5000:5000"
    # command: mlflow server --host 0.0.0.0
  
  fastapi_server:
    image: fastapi-server
    container_name: fastapi-server
    build: src/fastapi/.
    # entrypoint: python3 run.py
    # ports:
    #   - "8090:8090"